# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTc2():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_tc2(self):
        self.driver.get(
            "https://www.google.com/search?q=google&oq=google&aqs=chrome..69i57j0i131i433i512l4j69i60l3.2293j0j4&sourceid=chrome&ie=UTF-8")
        self.driver.set_window_size(1905, 1012)
        element = self.driver.find_element(By.LINK_TEXT, "Google Maps")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".tF2Cxc > .yuRUbf .LC20lb")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".tF2Cxc > .yuRUbf .LC20lb").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, "#L2AGLb > .QS5gu").click()
        self.driver.find_element(By.ID, "APjFqb").click()
        self.driver.find_element(By.ID, "APjFqb").send_keys("selenium")
        self.driver.find_element(By.CSS_SELECTOR, ".eKjLze .LC20lb").click()

